title: Eclectic Vibe Ventures LLC
description: Where tech slows down and sound becomes sanctuary
show_downloads: false
google_analytics:
#theme: jekyll-theme-cayman
remote_theme: tuur29/pages-themes-cayman
colors:
    gradient_left: "#e437e6"
    gradient_right: "#7e1abe"
    header: "#fff"
#    android_theme: "#000" # this default to gradient_color
#    link: "#1e6bb8" # this default to gradient_color
#    section_title: "#155799" # this default to gradient_color